---
resource_types:
  - name: rocketchat
    type: docker-image
    source:
      repository: michaellihs/rocket-notify-resource
      tag: dev-13

resources:
  - name: rocketchat
    type: rocketchat
    source:
      url: http://rocketchat:3000
      user: admin
      password: admin
      debug: 1

jobs:
  - name: rocketchat-notify
    plan:
      - task: successful-job
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args:
              - hello world
        on_success:
          put: rocketchat
          params:
            channel: general
            message: Job 'successful-job' succeeded
      - task: failing-job
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: ls
            args:
              - no_such_file
        on_failure:
          put: rocketchat
          params:
            channel: general
            message: Job 'failing-notify' failed
            put: rocketchat

