resource_types:
  - name: rocketchat
    type: docker-image
    source:
      repository: michaellihs/rocket-notify-resource
      tag: latest

resources:
  - name: rocketchat
    type: rocketchat
    source:
      url: http://rocketchat:3000
      user: admin
      password: admin
      channel: 'lalaland'

jobs:
  - name: rocketchat-notify
    plan:
      - get: rocketchat
      - task: notify
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args:
              - hello world
        on_success:
          put: rocketchat