version: 2
jobs:
  build:
    working_directory: /docker-image
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build --no-cache -t rocketchat-notification-resource .
      - deploy:
          name: Push resource Docker image
          command: |
            apk update
            apk upgrade
            apk add bash
            bash -c 'version=$(git describe --tags); if [[ $version =~ ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$ ]] ; then docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}; ./build.sh ${version} ${DOCKER_REPO}; fi'

#workflows:
#  version: 2
#  build-push:
#    jobs:
#      - build
#      - push:
#          requires:
#            - build
#          filters:
#            tags:
#              only: /^\d+\.\d+\.\d+$/