version: 2
jobs:
  build:
    working_directory: /docker-image
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build --no-cache -t rocketchat-notification-resource .
  push:
    working-directory: /docker-image
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - deploy:
          name: Push application Docker image
          command: |
            version=$(git describe --tags)
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            ./build.sh ${version} ${DOCKER_REPO}

workflows:
  version: 2
  build-push:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/